export const REMOVE_CARD = 'REMOVE_CARD';
export const ADD_CARD = 'ADD_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const SET_LOCATION = 'SET_LOCATION';
export const ON_CLICK = 'ON_CLICK';
export const REMOVE_ON_CLICK = 'REMOVE_ON_CLICK';
export const REMOVE_LOCATIONS = 'REMOVE_LOCATIONS';
export const SET_DECK = 'SET_DECK';
export const CLEAR_CURRENT_DECK = 'CLEAR_CURRENT_DECK';
export const SET_WORD = 'SET_WORD';
export const CLEAR_CURRENT_WORD = 'CLEAR_CURRENT_WORD';

export const topics = [
  {
    ruTopic: 'Адрес',
    enTopic: 'Address',
  },
  {
    ruTopic: 'Вопросы',
    enTopic: 'Questions',
  },
  {
    ruTopic: 'Страны',
    enTopic: 'Countries',
  },
    {
    ruTopic: 'Языки',
    enTopic: 'Languages',
  },
  {
    ruTopic: 'Города',
    enTopic: 'Cities',
  },
  {
    ruTopic: 'Имена',
    enTopic: 'Names',
  },  
  {
    ruTopic: 'Дни недели',
    enTopic: 'Days of Week',
  },
  {
    ruTopic: 'Местоимения',
    enTopic: 'Pronouns',
  },
  {
    ruTopic: 'Учеба',
    enTopic: 'Study',
  },
  {
    ruTopic: 'Приветствия',
    enTopic: 'Greetings',
  },
  {
    ruTopic: 'Организации/Места',
    enTopic: 'Organizations',
  },
  {
    ruTopic: 'Профессии',
    enTopic: 'Professions',
  },
  {
    ruTopic: 'Числа',
    enTopic: 'Numbers',
  },
  {
    ruTopic: 'Прилагательные',
    enTopic: 'Adjectives',
  },
  {
    ruTopic: 'Глаголы',
    enTopic: 'Verbs',
  },
  {
    ruTopic: 'Разное',
    enTopic: 'Other',
  },

];

export const vocabulary = [
  {
    word: 'יום ראשון',
    vocalization: 'יום ראשון',
    translation: 'Воскресенье (день первый)',
    transcription: 'йом ришОн',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'יום שני',
    vocalization: 'יום שני',
    translation: 'Понедельник (день второй)',
    transcription: 'йом шэнИ',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'יום שלישי',
    vocalization: 'יום שלישי',
    translation: 'Вторник (день третий)',
    transcription: 'йом шлишИ',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'יום רביעי',
    vocalization: 'יום רביעי',
    translation: 'Среда (день четвертый)',
    transcription: 'йом рэвии',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'יום חמישי',
    vocalization: 'יום חמישי',
    translation: 'Четверг (день пятый)',
    transcription: 'йом хамиши',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'יום שישי',
    vocalization: 'יום שישי',
    translation: 'Пятница (день шестой)',
    transcription: 'йом шишИ',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'שבת',
    vocalization: 'שבת',
    translation: 'Суббота/шаббат',
    transcription: 'шаббАт',
    ruTopic: ['Дни недели'],
    enTopic: ['Days of Week'],
  },
  {
    word: 'מה',
    vocalization: 'מה',
    translation: 'Что?',
    transcription: 'ма',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'מי',
    vocalization: 'מי',
    translation: 'Кто?',
    transcription: 'ми',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'מאין',
    vocalization: 'מאין',
    translation: 'Откуда?',
    transcription: 'мэАйн',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'איפה',
    vocalization: 'איפה',
    translation: 'Где?',
    transcription: 'эйфо',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'למה',
    vocalization: 'למה',
    translation: 'Почему?',
    transcription: 'ламА',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'מתי',
    vocalization: 'מתי',
    translation: 'Когда?',
    transcription: 'матАй',
    ruTopic: ['Вопросы'],
    enTopic: ['Questions'],
  },
  {
    word: 'שרה',
    vocalization: 'שרה',
    translation: 'Сара',
    transcription: 'Сара',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'יצחק',
    vocalization: 'יצחק',
    translation: 'Ицхак',
    transcription: 'ИцхАк',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'רותי',
    vocalization: 'רותי',
    translation: 'Рути',
    transcription: 'РУти',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'יוסף',
    vocalization: 'יוספ',
    translation: 'Иосеф',
    transcription: 'ИОсеф',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'מרינה',
    vocalization: 'מרינה',
    translation: 'Марина',
    transcription: 'МарИна',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'דינה',
    vocalization: 'דינה',
    translation: 'Дина',
    transcription: 'ДИна',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'דניאל',
    vocalization: 'דניאל',
    translation: 'Даниэль',
    transcription: 'Даниэль',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'דורית',
    vocalization: 'דורית',
    translation: 'Дорит (ж.р.)',
    transcription: 'Дорит',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'מיכאל',
    vocalization: 'מיכאל',
    translation: 'Михаэль',
    transcription: 'Михаэль',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'סימה',
    vocalization: 'סימה',
    translation: 'Сима',
    transcription: 'Сима',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'אורי',
    vocalization: 'אורי',
    translation: 'Ури',
    transcription: 'Ури',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'רחל',
    vocalization: 'רחל',
    translation: 'Рахэль',
    transcription: 'РахЭль',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'ענת',
    vocalization: 'ענת',
    translation: 'Анат',
    transcription: 'Анат',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'גיון',
    vocalization: 'גיון',
    translation: 'Джон',
    transcription: 'Джон',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'בוריס',
    vocalization: 'בוריס',
    translation: 'Борис',
    transcription: 'Борис',
    ruTopic: ['Имена'],
    enTopic: ['Names'],
  },
  {
    word: 'ירושלים',
    vocalization: 'ירושלים',
    translation: 'Иерусалим',
    transcription: 'ЕршалАим',
    ruTopic: ['Города'],
    enTopic: ['Cities'],
  },
  {
    word: 'טבריה',
    vocalization: 'טבריה',
    translation: 'Тверия',
    transcription: 'ТвЕрия',
    ruTopic: ['Города'],
    enTopic: ['Cities'],
  },
  {
    word: 'אילת',
    vocalization: 'אילת',
    translation: 'Эйлат',
    transcription: 'Эйлат',
    ruTopic: ['Города'],
    enTopic: ['Cities'],
  },
  {
    word: 'תל-אביב',
    vocalization: 'תל-אביב',
    translation: 'Тель-Авив',
    transcription: 'Тель-АвИв',
    ruTopic: ['Города'],
    enTopic: ['Cities'],
  },
  {
    word: 'חיפה',
    vocalization: 'חיפה',
    translation: 'Хайфа',
    transcription: 'ХАйфа',
    ruTopic: ['Города'],
    enTopic: ['Cities'],
  },
  {
    word: 'ספרד',
    vocalization: 'ספרד',
    translation: 'Испания',
    transcription: 'ШпАнье',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'אנגליה',
    vocalization: 'אנגליה',
    translation: 'Англия',
    transcription: 'Эйнгланд',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },      
  {
    word: 'רוסיה',
    vocalization: 'רוסיה',
    translation: 'Россия',
    transcription: 'РУссиа',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'אוקראינה',
    vocalization: 'אוקראינה',
    translation: 'Украина',
    transcription: 'УкраИнэ',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'צרפת',
    vocalization: 'צרפת',
    translation: 'Франция',
    transcription: 'ФрАнкрайх',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'ישראל',
    vocalization: 'ישראל',
    translation: 'Израиль',
    transcription: 'ИсраЭл',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'עיראק',
    vocalization: 'עיראק',
    translation: 'Ирак',
    transcription: 'Ирак',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'איראן',
    vocalization: 'איראן',
    translation: 'Иран',
    transcription: 'Иран',
    ruTopic: ['Страны'],
    enTopic: ['Countries'],
  },
  {
    word: 'עברית',
    vocalization: 'עברית',
    translation: 'Иврит',
    transcription: 'Иврит',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'רוסית',
    vocalization: 'רוּסִית',
    translation: 'Русский',
    transcription: 'русИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'אנגלית',
    vocalization: 'אַנגלִית',
    translation: 'Английский',
    transcription: 'англИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'צרפתית',
    vocalization: 'צָרפָתִית',
    translation: 'Испанский',
    transcription: 'царфатИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'גרמנית',
    vocalization: 'גֶרמָנִית',
    translation: 'Немецкий',
    transcription: 'германИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'ספרדימ',
    vocalization: 'ספָרַדִית',
    translation: 'Французский',
    transcription: 'сфарадит',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'רומנית',
    vocalization: 'רומנית',
    translation: 'Румынский',
    transcription: 'романит',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'ערבית',
    vocalization: 'ערבית',
    translation: 'Арабский',
    transcription: 'арвИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'אמהרית',
    vocalization: 'אמהרית',
    translation: 'Амхарский',
    transcription: 'ам(х)арИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'יפנית',
    vocalization: 'יפנית',
    translation: 'Японский',
    transcription: 'яфанИт',
    ruTopic: ['Языки'],
    enTopic: ['Languages'],
  },
  {
    word: 'בית',
    vocalization: 'בית',
    translation: 'Дом',
    transcription: 'бАйт',
    ruTopic: ['Адрес'],
    enTopic: ['Address'],
  },
  {
    word: 'רחוב',
    vocalization: 'רחוב',
    translation: 'Улица',
    transcription: 'рэхОв',
    ruTopic: ['Адрес'],
    enTopic: ['Address'],
  },
  {
    word: 'דירה',
    vocalization: 'דירה',
    translation: 'Квартира',
    transcription: 'дирА',
    ruTopic: ['Адрес'],
    enTopic: ['Address'],
  },
  {
    word: 'מספר',
    vocalization: 'מספר',
    translation: 'Номер',
    transcription: 'миспАр',
    ruTopic: ['Адрес'],
    enTopic: ['Address'],
  },
  {
    word: 'יום טוב',
    vocalization: 'יוֹם טוֹב',
    translation: 'Хорошего дня',
    transcription: 'йом тов',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'בוקר טוב',
    vocalization: 'בּוֹקֶר טוֹב',
    translation: 'Хорошего утра',
    transcription: 'бОкер тов',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'ערב טוב',
    vocalization: 'עֶרֶב טוֹב',
    translation: 'Хорошего вечера',
    transcription: 'Эрев тов',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'לילה טןב',
    vocalization: 'לַילָה טוֹב',
    translation: 'Хорошей ночи',
    transcription: 'лАйла тов',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'סליחה',
    vocalization: 'סליחה',
    translation: 'Извините',
    transcription: 'слихА',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'תודה רבה',
    vocalization: 'תודה רבה',
    translation: 'Большое спасибо',
    transcription: 'тодА рабА',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'בבקשה',
    vocalization: 'בבקשה',
    translation: 'Пожалуйста',
    transcription: 'бевакашА',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'בהצלחה',
    vocalization: 'בְּהַצלָחָה',
    translation: 'Успеха',
    transcription: 'бе(h)ацлаха',
    ruTopic: ['Приветствия'],
    enTopic: ['Greetings'],
  },
  {
    word: 'אולפן',
    vocalization: 'אולפן',
    translation: 'Ульпан',
    transcription: 'ульпАн',
    ruTopic: ['Учеба', 'Организации/Места'],
    enTopic: ['Study', 'Organizations/Places'],
  },
  {
    word: 'אוניברסיטה',
    vocalization: 'אוניברסיטה',
    translation: 'Университет',
    transcription: 'унивенситА',
    ruTopic: ['Учеба', 'Организации/Места'],
    enTopic: ['Study', 'Organizations/Places'],
  },
  {
    word: 'תלמיד',
    vocalization: 'תלמיד',
    translation: 'Ученик',
    transcription: 'талмИд',
    ruTopic: ['Учеба'],
    enTopic: ['Study'],
  },
  {
    word: 'סטודנט',
    vocalization: 'סטודנט',
    translation: 'Студент',
    transcription: 'студЭнт',
    ruTopic: ['Учеба'],
    enTopic: ['Study'],
  },
  {
    word: 'מורה',
    vocalization: 'מורה',
    translation: 'Учительница',
    transcription: 'морА',
    ruTopic: ['Учеба', 'Профессии'],
    enTopic: ['Study', 'Professions' ],
  },
  {
    word: 'לומד',
    vocalization: 'לומד',
    translation: 'Учиться',
    transcription: 'ломЭд',
    ruTopic: ['Учеба'],
    enTopic: ['Study'],
  },
  {
    word: 'בית-ספר',
    vocalization: 'בית-ספר',
    translation: 'Школа (дом книги)',
    transcription: 'бЕйт сэфЭр',
    ruTopic: ['Учеба', 'Организации/Места'],
    enTopic: ['Study', 'Organizations/Places'],
  },
  {
    word: 'כיתה',
    vocalization: 'כיתה',
    translation: 'Класс',
    transcription: 'китА',
    ruTopic: ['Учеба'],
    enTopic: ['Study'],
  },
  {
    word: 'משטרה',
    vocalization: '',
    translation: 'Полиция',
    transcription: 'миштарА',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'בנק',
    vocalization: 'בנק',
    translation: 'Банк',
    transcription: 'банк',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'קפה',
    vocalization: 'קפה',
    translation: 'Кафе',
    transcription: 'кафе',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'ספרייה',
    vocalization: 'ספרייה',
    translation: 'Библиотека',
    transcription: 'сфирИя',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'מסעדה',
    vocalization: 'מסעדה',
    translation: 'Ресторан',
    transcription: 'мисадА',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'מפעל',
    vocalization: 'מפעל',
    translation: 'Завод',
    transcription: 'мифАль',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'חנות',
    vocalization: 'חנות',
    translation: 'Магазин',
    transcription: 'ханУт',
    ruTopic: ['Организации/Места'],
    enTopic: ['Organizations/Places'],
  },
  {
    word: 'פקיד',
    vocalization: 'פָּקִיד',
    translation: 'Чиновник/служащий',
    transcription: 'пакИд',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'רופא',
    vocalization: 'רופא',
    translation: 'Врач',
    transcription: 'рофЭ',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'מוכרת',
    vocalization: 'מוכרת',
    translation: 'Продавщица',
    transcription: 'мохэрЭт',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'מלצרית',
    vocalization: 'מלצרית',
    translation: 'Официантка',
    transcription: 'мельцарИт',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'שומר',
    vocalization: 'שומר',
    translation: 'Охранник',
    transcription: 'шомЭр',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'סופרת',
    vocalization: 'סופרת',
    translation: 'Писательница',
    transcription: 'софЭрет',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'עיתונאי',
    vocalization: 'עיתונאי',
    translation: 'Журналист',
    transcription: 'итонАи',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'מנהל',
    vocalization: 'מנהל',
    translation: 'Директор',
    transcription: 'мэнаЭл',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'עבודה',
    vocalization: 'עבודה',
    translation: 'Работа',
    transcription: 'аводА',
    ruTopic: ['Профессии'],
    enTopic: ['Professions'],
  },
  {
    word: 'אפס',
    vocalization: 'אֶפֶס',
    translation: 'Ноль',
    transcription: 'эфЭс',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'אחת',
    vocalization: 'אַחַת',
    translation: 'Один',
    transcription: 'ахАт',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'שמיים',
    vocalization: 'שְׁתַּיִים',
    translation: 'Два',
    transcription: 'штАйм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'שלוש',
    vocalization: 'שָׁלוֹשׁ',
    translation: 'Три',
    transcription: 'шалОш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'ארבע',
    vocalization: 'אַרְבַּע',
    translation: 'Четыре',
    transcription: 'арбА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'חמש',
    vocalization: 'חָמֵשׁ',
    translation: 'Пять',
    transcription: 'хамЭш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'שש',
    vocalization: 'שֵׁשׁ',
    translation: 'Шесть',
    transcription: 'шеш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'שבע',
    vocalization: 'שֶׁבַע',
    translation: 'Семь',
    transcription: 'шэвА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'שמונה',
    vocalization: 'שְׁמוֹנֶה',
    translation: 'Восемь',
    transcription: 'шмони',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'תשע',
    vocalization: 'תֵּשַׁע',
    translation: 'Девять',
    transcription: 'тэшА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'עשר',
    vocalization: 'עֶשֶׂר',
    translation: 'Десять',
    transcription: 'эсрЭ',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
  },
  {
    word: 'אפס',
    vocalization: 'אפס',
    translation: 'Ноль',
    transcription: 'эфЭс',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 0,
  },
  {
    word: 'אחת',
    vocalization: 'אחת',
    translation: 'Один',
    transcription: 'ахАт',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 1,
  },
  {
    word: 'שמיים',
    vocalization: 'שתיים',
    translation: 'Два',
    transcription: 'штАйм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 2,
  },
  {
    word: 'שלוש',
    vocalization: 'שלוש',
    translation: 'Три',
    transcription: 'шалОш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 3,
  },
  {
    word: 'ארבע',
    vocalization: 'ארבע',
    translation: 'Четыре',
    transcription: 'арбА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 4,
  },
  {
    word: 'חמש',
    vocalization: 'חמש',
    translation: 'Пять',
    transcription: 'хамЭш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 5,
  },
  {
    word: 'שש',
    vocalization: 'שש',
    translation: 'Шесть',
    transcription: 'шеш',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 6,
  },
  {
    word: 'שבע',
    vocalization: 'שבע',
    translation: 'Семь',
    transcription: 'шэвА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 7,
  },
  {
    word: 'שמונה',
    vocalization: 'שמונה',
    translation: 'Восемь',
    transcription: 'шмони',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 8,
  },
  {
    word: 'תשע',
    vocalization: 'תשע',
    translation: 'Девять',
    transcription: 'тэшА',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 9,
  },
  {
    word: 'עשר',
    vocalization: 'עשר',
    translation: 'Десять',
    transcription: 'эсрЭ',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 10,
},
{
  word: 'אחת עשרה',
  vocalization: 'אַחַת עֶשׂרֵה',
  translation: 'Одиннадцать',
  transcription: 'ахАт эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 11,
},
{
  word: 'שתיים עשרה',
  vocalization: 'שְׁתֵיים עֶשׂרֵה',
  translation: 'Двенадцать',
  transcription: 'штэйм эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 12,
},
{
  word: 'שלוש עשרה',
  vocalization: 'שְׁלוֹשׁ עֶשׂרֵה',
  translation: 'Тринадцать',
  transcription: 'шлош эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 13,
},
{
  word: 'ארבע עשרה',
  vocalization: 'אַרְבַּע עֶשׂרֵה',
  translation: 'Четырнадцать',
  transcription: 'арбА эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 14,
},
{
  word: 'חמש עשדה',
  vocalization: 'חֲמֵשׁ עֶשׂרֵה',
  translation: 'Пятнадцать',
  transcription: 'хамЭш эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 15,
},
{
  word: 'שש עשדה',
  vocalization: 'שֵׁשׁ עֶשׂרֵה',
  translation: 'Шестнадцать',
  transcription: 'шеш эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 16,
},
{
  word: 'שבע עשדה',
  vocalization: 'שְׁבַע עֶשׂרֵה',
  translation: 'Семнадцать',
  transcription: 'шва эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 17,
},
{
  word: 'שמונה עשדה',
  vocalization: 'שְׁמוֹנֶה עֶשׂרֵה',
  translation: 'Восемнадцать',
  transcription: 'шмонЭ эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 18,
},
{
  word: 'תשע עשרה',
  vocalization: 'תְּשַׁע עֶשׂרֵה',
  translation: 'Девятнадцать',
  transcription: 'тша эсрЭ',
  ruTopic: ['Числа'],
  enTopic: ['Numbers'],
  num: 19,
},
{
    word: 'עשרים',
    vocalization: 'עֶשְׂרִים',
    translation: 'Двадцать',
    transcription: 'эсрИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 20,
},
{
    word: 'שלושים',
    vocalization: 'שׁלוֹשִים',
    translation: 'Тридцать',
    transcription: 'шлошИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 30,
}, 
{
    word: 'ארבעים',
    vocalization: 'אַרְבָּעִים',
    translation: 'Сорок',
    transcription: 'арбаИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 40,
},
{
    word: 'חמישים',
    vocalization: 'חֲמִישִׁים',
    translation: 'Пятьдесят',
    transcription: 'хамишИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 50,
},
{
    word: 'ששים',
    vocalization: 'שִׁשִׁים',
    translation: 'Шестьдесят',
    transcription: 'шишИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 60,
},
{
    word: 'שבעים',
    vocalization: 'שִׁבְעִים',
    translation: 'Семьдесят',
    transcription: 'шивИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 70,
},
{
    word: 'שמונים',
    vocalization: 'שְׁמוֹנִים',
    translation: 'Восемьдесят',
    transcription: 'шмонИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 80,
},
{
    word: 'משעים',
    vocalization: 'תִּשְׁעים',
    translation: 'Девяносто',
    transcription: 'тишИм',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 90,
  },
  {
    word: 'מאה',
    vocalization: 'מאה',
    translation: 'Сто',
    transcription: 'мЭа',
    ruTopic: ['Числа'],
    enTopic: ['Numbers'],
    num: 100,
  },
  {
    word: 'אני',
    vocalization: 'אני',
    translation: 'Я',
    transcription: 'анИ',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'את',
    vocalization: 'אמ',
    translation: 'Ты (ж.р.)',
    transcription: 'ат',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'אמה',
    vocalization: 'אתה',
    translation: 'Ты (м.р.)',
    transcription: 'атА',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'הוא',
    vocalization: 'הוא',
    translation: 'Он',
    transcription: '(х)у',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'היא',
    vocalization: 'היא',
    translation: 'Она',
    transcription: '(х)и',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'אנחנו',
    vocalization: 'אנחנו',
    translation: 'Мы',
    transcription: 'анАхну',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'הן',
    vocalization: 'הן',
    translation: 'Они (ж.р)',
    transcription: '(х)Эн',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'הם',
    vocalization: 'הם',
    translation: 'Они (м.р.)',
    transcription: '(х)Эм',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'אתן',
    vocalization: 'אתן',
    translation: 'Вы (ж.р.)',
    transcription: 'атЭн',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'אמם',
    vocalization: 'אמם',
    translation: 'Вы (м.р.)',
    transcription: 'атЭм',
    ruTopic: ['Местоимения'],
    enTopic: ['Pronouns'],
  },
  {
    word: 'טוב',
    vocalization: 'טוב',
    translation: 'Хороший',
    transcription: 'тов',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'זול',
    vocalization: 'זול',
    translation: 'Дешевый',
    transcription: 'зол',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },  
  {
    word: 'קטן',
    vocalization: 'קטן',
    translation: 'Маленький',
    transcription: 'катАн',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'יקר',
    vocalization: 'יקר',
    translation: 'Дорогой (денежно)',
    transcription: 'йакАр',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'גדול',
    vocalization: 'גדול',
    translation: 'Большой',
    transcription: 'гадОль',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'יפה',
    vocalization: 'יפה',
    translation: 'Красивый',
    transcription: 'йафЭ',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'חשוב',
    vocalization: 'חשוב',
    translation: 'Важный',
    transcription: 'хашУв',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'מעניין',
    vocalization: 'מעניין',
    translation: 'Интересный',
    transcription: 'мэанИн',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'נחמד',
    vocalization: 'נחמד',
    translation: 'Милый',
    transcription: 'нэхмАд',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'קצר',
    vocalization: 'קצר',
    translation: 'Короткий',
    transcription: 'кацАр',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'ארוך',
    vocalization: 'ארוך',
    translation: 'Длинный',
    transcription: 'арОх',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'קל',
    vocalization: 'קל',
    translation: 'Легкий',
    transcription: 'кал',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'מפורסם',
    vocalization: 'מפורסם',
    translation: 'Известный',
    transcription: 'мэфурсАм',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'מעניין',
    vocalization: 'מעניין',
    translation: 'Интересный',
    transcription: 'маниЭн',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'קשה',
    vocalization: 'קשה',
    translation: 'Трудный',
    transcription: 'кашЭ',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'חדש',
    vocalization: 'חדש',
    translation: 'Новый',
    transcription: 'хадАш',
    ruTopic: ['Прилагательные'],
    enTopic: ['Adjectives'],
  },
  {
    word: 'לוֹמֵד',
    vocalization: 'לוֹמֵד',
    translation: '(он) учится',
    transcription: 'ломЭд',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'עובד',
    vocalization: 'עוֹבֵד',
    translation: '(он) работает',
    transcription: 'овЭд',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'מדבר',
    vocalization: 'צדבר',
    translation: '(он) говорит',
    transcription: 'медабЭр',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'מצטער',
    vocalization: 'מצטער',
    translation: '(он) огорчается',
    transcription: 'мицтаЭр',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'יודע',
    vocalization: 'יודע',
    translation: '(он) знает',
    transcription: 'йодЭ',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'מבין',
    vocalization: 'מבין',
    translation: '(он) понимает',
    transcription: 'мавИн',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'כותב',
    vocalization: 'כותב',
    translation: '(он) пишет',
    transcription: 'котЭв',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'קורא',
    vocalization: 'קורא',
    translation: '(он) читает',
    transcription: 'корЭ',
    ruTopic: ['Глаголы'],
    enTopic: ['Verbs'],
  },
  {
    word: 'מטייל',
    vocalization: 'מטייל',
    translation: '(он) гуляет/путешествует',
    transcription: 'митайЭл',
    ruTopic: ['Глаголы', 'Путешествия'],
    enTopic: ['Verbs', 'Travel'],
  },
  {
    word: 'תייר',
    vocalization: 'תייר',
    translation: 'Турист',
    transcription: 'таЯр',
    ruTopic: ['Путешествия'],
    enTopic: ['Travel'],
  },
  {
    word: 'טלפון',
    vocalization: 'טלפון',
    translation: 'Телефон',
    transcription: 'Тэлэфон',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'עולה חדש',
    vocalization: 'עולה חדש',
    translation: 'Новый репатриант',
    transcription: 'олЕ хадАш',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'קצת',
    vocalization: 'קצת',
    translation: 'Ненадолго',
    transcription: 'Кцат',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'גם',
    vocalization: 'גם',
    translation: 'Тоже',
    transcription: 'гам',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'בן',
    vocalization: 'בן',
    translation: 'Да',
    transcription: 'кен',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'לא',
    vocalization: 'לא',
    translation: 'нет',
    transcription: 'лЁ',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'נכון',
    vocalization: 'נכון',
    translation: 'Верно',
    transcription: 'нахОн',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'שולחן',
    vocalization: 'שולחן',
    translation: 'Стол',
    transcription: 'шулхАн',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'תמןנה',
    vocalization: 'תמונה',
    translation: 'Картина',
    transcription: 'тмунА',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'עט',
    vocalization: 'עט',
    translation: 'Ручка',
    transcription: 'эт',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'עיתון',
    vocalization: 'עימון',
    translation: 'Газета',
    transcription: 'итон',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'סיפור',
    vocalization: 'סיפור',
    translation: 'История',
    transcription: 'сипОр',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'ספר',
    vocalization: 'ספר',
    translation: 'Книга',
    transcription: 'сэфЭр',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'מכתב',
    vocalization: 'תכתב',
    translation: 'Письмо',
    transcription: 'миктАв',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'תיק',
    vocalization: 'תיק',
    translation: 'Сумка',
    transcription: 'тик',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'שאלה',
    vocalization: 'שאלה',
    translation: 'Вопрос',
    transcription: 'шЭЭла',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'מחשב',
    vocalization: 'מחשב',
    translation: 'Мысль',
    transcription: 'махашЭв',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'מחשב',
    vocalization: 'מחשב',
    translation: 'Компьютер',
    transcription: 'махшЕв',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'מאוד',
    vocalization: 'מאוד',
    translation: 'Очень',
    transcription: 'мэОд',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'נעים',
    vocalization: 'נעים',
    translation: 'Приятно',
    transcription: 'нАйм',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'בחורה',
    vocalization: 'בחורה',
    translation: 'Девушка',
    transcription: 'бахурА',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'בחור',
    vocalization: 'בחור',
    translation: 'Парень',
    transcription: 'бахУр',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  
  {
    word: 'חופש',
    vocalization: 'חופש',
    translation: 'Отпуск',
    transcription: 'хофЭш',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'רק',
    vocalization: 'רק',
    translation: 'Только',
    transcription: 'рак',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'עכשיב',
    vocalization: 'עכשיב',
    translation: 'Сейчас',
    transcription: 'ахшИв',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
  {
    word: 'הדיאלוג',
    vocalization: 'הדיאלוג',
    translation: 'Диалог',
    transcription: 'диалог',
    ruTopic: ['Разное'],
    enTopic: ['Other'],
  },
];
